nodeExporter:
  enabled: false

alertmanager:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

kubeApiServer:
  enabled: false

kubeApiServer:
  enabled: false

kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

prometheusOperator:
  enabled: false


grafana:
  extraConfigmapMounts: 
  - name: simplified-mainnet-dashboard
    mountPath: /var/lib/grafana/dashboards
    configMap: simplified-mainnet-dashboard
    readOnly: true